//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public string macuahang { get; set; }
        public string makhuyenmai { get; set; }
        public string diachi { get; set; }
        public Nullable<int> adminID { get; set; }
    
        public virtual QuanTriVien QuanTriVien { get; set; }
    }
}
