//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string madanggia { get; set; }
        public string maKH { get; set; }
        public string noidung { get; set; }
        public Nullable<int> sosao { get; set; }
        public Nullable<System.DateTime> ngayDanhGia { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
