//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string makhuyenmai { get; set; }
        public string mota { get; set; }
        public int thoigianhieuluc { get; set; }
        public string masanphamKM { get; set; }
    
        public virtual SanPhamKhuyenMai SanPhamKhuyenMai { get; set; }
    }
}
