//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamKhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamKhuyenMai()
        {
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public string MaSanPhamKM { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaKhuyenMai { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
