//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamKhuyenMai1
    {
        public int MaSanPhamKM { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaKhuyenMai { get; set; }
        public System.DateTime ThoiGianHieuLuc { get; set; }
    }
}
